const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{Personagem1: 0},
	{Fixar: 0},
	{Lutador1player1: 0},
	{Personagem2: 0},
	{Lutador2player1: 0},
	{Sólido: 0},
	{Ground: 0},
	{Fade: 0},
	{Logo: 0},
	{botãoIniciar: 0},
	{botãoOpções: 0},
	{Seleção1: 0},
	{Seleção2: 0},
	{Personagem3: 0},
	{Seleção3: 0},
	{Personagem4: 0},
	{Seleção4: 0},
	{Exibidor1: 0},
	{Exibidor2: 0},
	{BotãoContinue: 0},
	{BotãoDesistir: 0},
	{PersonagemFerrado: 0},
	{ContadorTempo: 0},
	{VidaPersonagem1: 0},
	{VidaPersonagem2: 0},
	{NomePersonagem1: 0},
	{NomePersonagem2: 0},
	{ContadorTempoLuta: 0},
	{BarraEspecial: 0},
	{EspecialFundo: 0},
	{BGTOTAL: 0},
	{Piscar: 0},
	{LOGOTITULOSPLASHJOGO: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{Audio: 0},
	{Selecionador: 0},
	{Selecionador2: 0},
	{Lutador3player2: 0},
	{Lutador4player1: 0},
	{CarregarPersonagem: 0},
	{Vida: 0},
	{VidaMaxima: 0},
	{Especial: 0},
	{PontoRound: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{ContainerPlayer1: 0},
	{ContainerPlayer2: 0},
	{Pausado: 0},
	{MenuTempo: 0},
	{SanguePersonagem1: 0},
	{SanguePersonagem2: 0},
	{EspecialFundo2: 0},
	{Energia01: 0},
	{Energia02: 0},
	{InfoDoJogo: 0},
	{InfoDoJogo2: 0},
	{InfoDoJogo3: 0},
	{InfoDoJogo4: 0},
	{InfoDoJogo5: 0},
	{InfoDoJogo6: 0},
	{InfoDoJogo7: 0},
	{Camera: 0},
	{ZoomOut1: 0},
	{ZoomOut2: 0},
	{BG: 0},
	{CentrarEm: 0},
	{CameraLutadores: 0},
	{PlanoDeFundoEmBlocos: 0},
	{BGSelecao: 0},
	{TituloSelecao: 0},
	{OSanguePlayer2: 0},
	{NomePlayer1: 0},
	{NomePlayer2: 0},
	{Round1: 0},
	{NomePlayer1Luta: 0},
	{NomePlayer1Luta2: 0},
	{BGMenu: 0},
	{botãoOpções2: 0},
	{Lutador1player2: 0},
	{Lutador2player2: 0},
	{Lutador3player1: 0},
	{Lutador4player2: 0},
	{botãoOpções3: 0},
	{BotãoContinue2: 0},
	{Nuvens: 0},
	{NuvensParalax: 0},
	{FundoFundo: 0},
	{BGContinue: 0},
	{Projétil: 0},
	{BolaVolei: 0},
	{DestruirForaDoLayout: 0},
	{Prancha: 0},
	{InfoDoJogo8: 0},
	{GatilhoEspecial: 0},
	{EspecialTela: 0},
	{EspecialFull: 0},
	{EspecialFull2: 0},
	{Impacto: 0},
	{Round1Player1: 0},
	{Round1Player2: 0},
	{Round2Player2: 0},
	{Round2Player1: 0},
	{Impacto2: 0},
	{Mouse: 0},
	{MenuComandos: 0},
	{FechaJanela: 0},
	{Cronometro: 0},
	{EspecialCPU: 0},
	{VitoriaPlayer1: 0},
	{VitoriaPlayer2: 0},
	{Personagem1Selecionado: 0},
	{Personagem2Selecionado: 0},
	{Personagem1Player1: 0},
	{Personagem1Player2: 0},
	{Personagem2Player1: 0},
	{Personagem2Player2: 0},
	{Personagem3Player1: 0},
	{Personagem3Player2: 0},
	{Personagem4Player1: 0},
	{Personagem4Player2: 0},
	{Personagem3Player3: 0},
	{CronometroContinue: 0}
];

self.InstanceType = {
	Lutador1player1: class extends self.ISpriteInstance {},
	Lutador2player1: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	botãoIniciar: class extends self.ISpriteInstance {},
	botãoOpções: class extends self.ISpriteInstance {},
	Seleção1: class extends self.ISpriteInstance {},
	Seleção2: class extends self.ISpriteInstance {},
	Seleção3: class extends self.ISpriteInstance {},
	Seleção4: class extends self.ISpriteInstance {},
	Exibidor1: class extends self.ISpriteInstance {},
	Exibidor2: class extends self.ISpriteInstance {},
	BotãoContinue: class extends self.ISpriteInstance {},
	BotãoDesistir: class extends self.ISpriteInstance {},
	PersonagemFerrado: class extends self.ISpriteInstance {},
	ContadorTempo: class extends self.ITextInstance {},
	VidaPersonagem1: class extends self.ISpriteInstance {},
	VidaPersonagem2: class extends self.ISpriteInstance {},
	NomePersonagem1: class extends self.ITextInstance {},
	NomePersonagem2: class extends self.ITextInstance {},
	ContadorTempoLuta: class extends self.ITextInstance {},
	BarraEspecial: class extends self.ISpriteInstance {},
	EspecialFundo: class extends self.ISpriteInstance {},
	BGTOTAL: class extends self.ISpriteInstance {},
	LOGOTITULOSPLASHJOGO: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Selecionador: class extends self.ISpriteInstance {},
	Selecionador2: class extends self.ISpriteInstance {},
	Lutador3player2: class extends self.ISpriteInstance {},
	Lutador4player1: class extends self.ISpriteInstance {},
	ContainerPlayer1: class extends self.ISpriteInstance {},
	ContainerPlayer2: class extends self.ISpriteInstance {},
	MenuTempo: class extends self.ISpriteInstance {},
	SanguePersonagem1: class extends self.ITiledBackgroundInstance {},
	SanguePersonagem2: class extends self.ITiledBackgroundInstance {},
	EspecialFundo2: class extends self.ISpriteInstance {},
	Energia01: class extends self.ITiledBackgroundInstance {},
	Energia02: class extends self.ITiledBackgroundInstance {},
	InfoDoJogo: class extends self.ITextInstance {},
	InfoDoJogo2: class extends self.ITextInstance {},
	InfoDoJogo3: class extends self.ITextInstance {},
	InfoDoJogo4: class extends self.ITextInstance {},
	InfoDoJogo5: class extends self.ITextInstance {},
	InfoDoJogo6: class extends self.ITextInstance {},
	InfoDoJogo7: class extends self.ITextInstance {},
	Camera: class extends self.ISpriteInstance {},
	ZoomOut1: class extends self.ISpriteInstance {},
	ZoomOut2: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	CameraLutadores: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	BGSelecao: class extends self.ITiledBackgroundInstance {},
	TituloSelecao: class extends self.ISpriteInstance {},
	OSanguePlayer2: class extends self.ITiledBackgroundInstance {},
	NomePlayer1: class extends self.ISpriteInstance {},
	NomePlayer2: class extends self.ISpriteInstance {},
	Round1: class extends self.ISpriteInstance {},
	NomePlayer1Luta: class extends self.ISpriteInstance {},
	NomePlayer1Luta2: class extends self.ISpriteInstance {},
	BGMenu: class extends self.ITiledBackgroundInstance {},
	botãoOpções2: class extends self.ISpriteInstance {},
	Lutador1player2: class extends self.ISpriteInstance {},
	Lutador2player2: class extends self.ISpriteInstance {},
	Lutador3player1: class extends self.ISpriteInstance {},
	Lutador4player2: class extends self.ISpriteInstance {},
	botãoOpções3: class extends self.ISpriteInstance {},
	BotãoContinue2: class extends self.ISpriteInstance {},
	Nuvens: class extends self.ISpriteInstance {},
	NuvensParalax: class extends self.ITiledBackgroundInstance {},
	FundoFundo: class extends self.ITiledBackgroundInstance {},
	BGContinue: class extends self.ITiledBackgroundInstance {},
	BolaVolei: class extends self.ISpriteInstance {},
	Prancha: class extends self.ISpriteInstance {},
	InfoDoJogo8: class extends self.ITextInstance {},
	GatilhoEspecial: class extends self.ISpriteInstance {},
	EspecialTela: class extends self.ISpriteInstance {},
	EspecialFull: class extends self.ISpriteInstance {},
	EspecialFull2: class extends self.ISpriteInstance {},
	Impacto: class extends self.ISpriteInstance {},
	Round1Player1: class extends self.ISpriteInstance {},
	Round1Player2: class extends self.ISpriteInstance {},
	Round2Player2: class extends self.ISpriteInstance {},
	Round2Player1: class extends self.ISpriteInstance {},
	Impacto2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	MenuComandos: class extends self.ISpriteInstance {},
	FechaJanela: class extends self.ISpriteInstance {}
}